- package-lock.json
- package.json
- src/schema.ts
- src/typegoose.ts
- test/models/discriminators.ts
- test/tests/shouldRun.test.ts
- adding discriminator support
- use "sch.clone()" to clone before assigning to avoid having the properties in the parent schema
better (& working) version of szokodiakos#333
> Adding Discriminator support

- src/typegoose.ts
- test/tests/shouldRun.test.ts
Please consider merging this as being able to override model options (existingMongoose) is very useful in tests.
> Add back options parameter to getModelForClass

- src/internal/utils.ts
- test/tests/shouldRun.test.ts
Fixes a bug with different options for the same model. 
The `mergeMetadata` function modified the current metadata instead of returning a modified copy.
> Change behaviour to not modify metadata object in merge function

- github-page/_guides/advanced/models-with-same-name.md
- github-page/_guides/quick-start-guide.md
- temporarily move broken link to tests to r6 branch link
- fix minor typo in quick start guide about new vs create
- add minor gotcha to quick start guide about inferred types
> DOC: fix some minor documentation quirks

- src/prop.ts
When a class has n properties using the same subclass, the
function `baseProp` is called n times for each property in subclass.
The function `baseProp` receives a parameter `rawOptions` which
should be copied as its being mutated later on. This is intended with
the statement:
```
rawOptions = Object.assign(rawOptions, {})
```
Although, this statement never changes the reference of `rawOptions`
with as result that the options are mutating. This causes the final schema
to be constructed without the options ref, itemsRef, refPath, etc when
the subclass is used more than once.
This commit fixes the mutation of the options.
Signed-off-by: Chris Lahaye <dev@chrislahaye.com>
> Fix decorator options mutating (fixes #55)

- .travis.yml
- .vscode/settings.json
- README.md
- github-page/_guides/quick-start-guide.md
- github-page/changelog.md
- github-page/index.md
- package-lock.json
- package.json
- src/defaultClasses.ts
- src/globalOptions.ts
- src/hooks.ts
- src/index.ts
- src/internal/schema.ts
- src/internal/utils.ts
- src/plugin.ts
- src/prop.ts
- src/typegoose.ts
- src/types.ts
- test/models/persistentModel.ts
- test/models/user.ts
- test/tests/dClasses.test.ts
- test/tests/errors.test.ts
- test/tests/getClassForDocument.test.ts
- test/tests/globalOptions.test.ts
- test/tests/inheritance.test.ts
- test/tests/overwrittenModel.test.ts
- test/tests/shouldAdd.test.ts
- test/tests/shouldRun.test.ts
- test/utils/config.ts
- test/utils/mongooseConnect.ts
well... typescript 3.7 is not released yet
Typescript aims to release 3.7 at 5.11.2019 (d/m/y)
- refactor to use the new "Optional Chaining"
- refactor to use the new "Nullish Coalescing"
- enhances many checks to be more explicit
- check if some checks can be replaced with "Assertion Functions"
- update to latest code base when 3.7 comes out
---
closes typegoose#56
> Upgrade to Typescript 3.7

- README.md
Modify README to link to the correct guides page
The link previously linked to https://typegoose.github.io/typegoose/guides (doesn't exist). I've changed it to link https://typegoose.github.io/typegoose/guides/quick-start-guide/ (has the same effect as going to homepage and clicking "Guides").
- changes a link to point to the correct url to make sure the user goes to the guides page
This PR is finished.
> Fix guides link in README.md

- github-page/_docs/decorators/prop.md
- github-page/_docs/virtuals.md
Adding documentation for:
- settings to return virtual props on json
- select prop options
Implements #167 #174
- closes #167
- closes #174
> docs: virtual props and select prop option

- src/plugin.ts
With `T extends any | any[]` I can't type options with a interface
> Fix plugins generic type

- src/types.ts
- test/tests/shouldAdd.test.ts
A small fix to remove type inference document's properties on model.
```ts
UserModel.firstName // Got Property 'firstName' does not exist on type 'ReturnModelType<typeof User, unknown>'
```
- fixes #220
> Remove type inference document's properties on model.

- src/types.ts
- test/models/refTests.ts
- test/tests/ref.test.ts
When `Ref<RefClass>` was used on a class defined with an optional `_id?` property that was not of type `ObjectId`, the extracted type would be wrong.
See [TypeScript Playground](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=36&pc=3#code/C4TwDgpgBA8gRgKwgY2ASQCZQLxQN5QDOA9gLYTAAWAlgHYDmAXFMAE4Cu0AvgNwBQoSFABC7AGZiIrHPl595EAB5hirYFAwoANgENW0QdABKEMQBVw0XLXak4UqAB8ibOvSexEKdFmeiJUvx8SipqLJawWhgmYgA8RgA0UGZQSsAQtBiEUDEWQrhGqYrpmdkEAPrUGMy5ljxQXFAA-DkA2gDklRjtALpQzPBIqJgAfDKFzmZBIarqmsi6+uFCMfFJKWkZWTmmeVY5RSXbeHxQZ1BdTTW7dXyNLQByxLQP7Fq6cFoQ8R1dvWMDLzDDBjAoeKbyPgLHSEbIAWWImi0AEF8KcLlUri5WG5+Fx5NDYVAEUjhGizl0AITMQiuBgediZUx0CAYPEE3REkkQLTkqD0YiImLUnZxbkokb8M4CoWmABMItW4uEkvkZzgOmiphFMCiSsRPORqvVmpiCoGetMsXFRvZUOetKgYkFzHFMhO0sFWrEzAARJQeVpiL6EuiZd65X6A+9g6H0RrvVHA7H46b5UmYyG7jwgA) for …
> fix: Ref<> type broken with optional property

- src/queryMethod.ts
- test/tests/shouldRun.test.ts
This PR fixes getting metadata from a class for query methods.
I've hit the error when I tried to apply multiple query methods to a schema.
**Notes**
Moved metadata test before document creation to raise error in case metadata is not correct before doing anything else in the database.
> Fix query method decorator

- github-page/_docs/decorators/queryMethod.md
- github-page/_docs/types/returnModelType.md
- github-page/changelog.md
- src/internal/schema.ts
- src/internal/utils.ts
- src/queryMethod.ts
- src/typegoose.ts
- src/types.ts
- test/tests/shouldRun.test.ts
This is the only thing I could think of for query methods types. Using mongoose's own types for `Model`'s `QueryHelpers`, which is added as the third type argument to the `getModelForClass` function.
- closes #236
> Types for query methods

- src/typegoose.ts
The logic is trying to warn developer about the old node version using a logger, but the logger is not yet imported there. This causes a reference error instead of that warning.
This change moves the logger import before the check, so that it's in the scope when warning is happening and the logic proceeds correctly.
To verify: attempt to run the typegoose logic before and after the change on an older node version.
> Imports the logger earlier to fix reference error

- src/internal/processProp.ts
- src/internal/utils.ts
- src/types.ts
- test/models/refTests.ts
- test/tests/ref.test.ts
If the model class extends with the `Base<string>`, the `DocumentType` definition is bad because the conditional type uses `Base` instead of `Base<any>`. The default value for the generic of `Base` class is `ObjectId` so the test in conditional type is `T extends Base<ObjectId>`.
```typescript
class Test extends Base<string> {}
const TestModel = getModelForClass(Test);
const test = new TestModel();
test._id; // <= _id have the any type instead of string
```
> fix the DocumentType definition when the model extends Base<String>

- github-page/_docs/decorators/prop.md
The documentation of the `type` option in the `@prop` decorator suggests that it is only necessary in edge cases. However, with the deprecation of `@arrayProp`, this option will become *mandatory* for any array properties.
This PR makes that clear, to avoid other developers debugging something that is a known behavior that can't be fixed.
- #300 
- #318 
- #321
> docs: document use of type option with arrays

- src/typegoose.ts
In a lot of environments, there is a polyfill for process used in client-side code. Checking the window is a better check for client-side vs server-side code.
- https://discordapp.com/channels/612400042900193311/612406912465502224/747832913260838982
> fix: improved client side check

- src/typegoose.ts
- test/tests/modelOptions.test.ts
```
export function addModelToTypegoose<U extends AnyParamConstructor<any>, QueryHelpers = {}>(
model: mongoose.Model<any>,
cl: U,
options?: { existingMongoose?: mongoose.Mongoose; existingConnection: any })
```
- add param `options?` to fix an issue when using an outside module for creating the connection with mongoose
when the connection is created in another module - the assertion fails and in reality `existingConnection` and `existingMongoose` do not work.
existingConnection is of type `any` and not `mongoose.Connection` since the mongoose types definition has no `base` for it. Without `base` there was no way to get the mongoose object for assertion.
> fix: add param for existingMongoose/existingConnection to addModelToTypegoose

- docs/api/virtuals.md
I read the docs about how to create virtual populate and ran into the same issues as described in #427. 
As far as I can see, circular dependencies can't be solved when using different classes.
So I thought it could be useful to update the docs with a better description by adding a link to the [ref doc](https://typegoose.github.io/typegoose/docs/api/decorators/prop/#ref) and adding the hint that one should use `'ClassName'` when the classes are in different files.
- fixes #427 (not a real fix, but prevents future 'bug' reports)
> docs(virtuals): improved description of ref option

- docs/api/decorators/prop.md
https://typegoose.github.io/typegoose/docs/api/decorators/prop/#default
the current default function example is invalid (using an arrow function)
arrow functions cant have this parameters
---
besides that, mongoose won't be able to bind `this` correctly if an arrow function is used instead of a function expression.
the example has to be either 
```ts
@prop({ 
default (this: DocumentType<User>) { 
return `${this.firstName} ${this.lastName}`
} 
}) fullName?: string
```
(why this is valid js https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions)
---
or the more verbose variant 
```ts
@prop({ 
default: function (this: DocumentType<User>) { 
return `${this.firstName} ${this.lastName}`
} 
}) fullName?: string
```
> fix invalide default function example

- docs/guides/error-warnings-details.md
- src/typegoose.ts
I was having some issues with my bundler (not typegoose's fault) and it would have been nice to have some diagnostic info about _why_ we were getting the wrong version. This adds the version seen to the error message about incorrect versions.
Adds a bit of diagnostic info to the E001 error message.
> Mongoose version diagnostic info.

- README.md
- docs/guides/error-warnings-details.md
- docs/guides/faq.md
- docs/guides/known-issues.md
- docs/guides/mongoose-compatibility.csv
- docs/guides/mongoose-compatibility.md
- docs/guides/quick-start-guide.md
- package.json
- src/defaultClasses.ts
- src/hooks.ts
- src/internal/schema.ts
- src/internal/utils.ts
- src/queryMethod.ts
- src/typegoose.ts
- src/typeguards.ts
- src/types.ts
- test/tests/arrayValidator.test.ts
- test/tests/biguser.test.ts
- test/tests/discriminators.test.ts
- test/tests/getClassForDocument.test.ts
- test/tests/shouldAdd.test.ts
- test/tests/shouldRun.test.ts
- test/tests/stringValidator.test.ts
- yarn.lock
Change Typegoose to be compatible with mongoose 5.11+
Before Merging, some things need to happen before:
- mongoose version 5.11.19 being released, which included official QueryMethods
- https://github.com/Automattic/mongoose/issues/9980 as an sidenote
- this change needs to be tested
- fixes #432
> Update to be compatible with mongoose@5.11+

- src/internal/schema.ts
- src/internal/utils.ts
- src/typegoose.ts
- test/tests/customName.test.ts
- test/tests/overwrittenModel.test.ts
This PR adds an customOptions optional field to `getName`. The function will priorize `options.customName`, `options.automaticName` and `schemaOptions.collection` provided in `customOptions` over the ones extracted via Reflection.
With this, `getModelForClass` can send the options it receveid to `getName`, fixing the issue where those fields, when provided via options to `getModelForClass` were not taken into account.
fixes #495
> feat(getModelForClass): use customName and automaticName from options (#495)

- docs/guides/advanced/array-types.md
- website/sidebars.js
- array types
I have added a page to the `Advanced` part of the documentation, which covers the case in the #509 issue.  If the whole page is too much, I am ready to extend information in any other of the existing doc pages. But I thought, that having a separate page in the `Advanced` area of the site, Is much better because it could be useful to have it in the future and add other information, that could be relative to the array fields.
I hope that PR has been made correctly and will be approved by @hasezoey
- #509
> docs(array-types) - added array types page

- src/index.ts
- test/models/indexweigths.ts
The `index` decorator does not have enforced typing in its arguments by default.
When tried the following:
```ts
@index<User>({name:1})
class User{
@prop()
name!: string
@prop()
email!:string
}
```
It gave 2 errors:
1. `email` field missing
2. `name` field has to be of type string
which are non-legitimate exceptions.
```ts
@index<Partial<Records<keyof User,any>>&{[key:string]:any}>({name:1})
// ...
```
This PR technically only implements the workaround above inside this lib itself.
> add convenience typing of index decorator

- src/defaultClasses.ts
Fix TS2554 error when trying to use findOrCreate() with two parameters.
The findOrCreate() implementation takes a second parameter to pass values that are added to the filter values to create a new Document.
[drudge/mongoose-findorcreate#usage](https://github.com/drudge/mongoose-findorcreate#usage)
> You can also include properties that aren't used in the find call, but will be added to the object if it is created.
>```js
>Click.create({ip: '127.0.0.1'}, {browser: 'Mozilla'}, function(err, val) {
>  Click.findOrCreate({ip: '127.0.0.1'}, {browser: 'Chrome'}, function(err, click) {
>   console.log('A click from "%s" using "%s" was found', click.ip, click.browser);
>    // prints A click from "127.0.0.1" using "Mozilla" was found
>  })
>});
>```
Current declaration doesn't reflect that.
--- …
> fix(defaultClasses): add missing 2nd parameter for findOrCreate() +

- package.json
- yarn.lock
I use typegoose and npm 7 in my project. npm 7 installs peer dependencies by default. Since typegoose has `"@types/mongoose": "^5.10.2"` as a peer dependency, npm installs `"@types/mongoose": "5.11.x"` which in turn doesn't have types anymore. For this reason I changed `^5.10.2` to `~5.10.2`
> chore: lock @types/mongoose version to 5.10 minor in dev and peer dependencies

- docs/api/decorators/prop.md
- src/internal/processProp.ts
- src/typegoose.ts
- test/tests/shouldRun.test.ts
Add the `Passthrough` class to directly embed paths, like mongoose would allow
- fixes typegoose/typegoose#382
---
~~WIP because it still needs testing~~
> feat: add class "Passthrough" and functionality

- docs/guides/quick-start-guide.md
Since one of the notes says:
> - Do not use Arrow Functions, because it will break the binding of `this`
The hooks usage example shouldn't expose arrow functions as a valid way to use it
> docs(quick-start-guide): remove arrow function in hooks example

- docs/guides/advanced/class-transformer.md
- docs/guides/advanced/deepkit-type.md
- package.json
- test/tests/__snapshots__/deepkitType.test.ts.snap
- test/tests/deepkitType.test.ts
- website/sidebars.js
- yarn.lock
This PR adds tests and some documentation for using @deepkit/type with Typegoose for serialization and deserialization.
- fixes #601 
Scott
> feat: adds tests and docs for @deepkit/type

- docs/api/decorators/prop.md
- docs/guides/advanced/class-transformer.md
- docs/guides/migrate-9.md
- docs/guides/mongoose-compatibility.csv
- docs/guides/mongoose-compatibility.md
- package.json
- src/internal/utils.ts
- src/typegoose.ts
- src/types.ts
- test/globalSetup.ts
- test/tests/__snapshots__/biguser.test.ts.snap
- test/tests/classTransformer.test.ts
- test/tests/ref.test.ts
- test/tests/shouldAdd.test.ts
- test/tests/shouldRun.test.ts
- test/tests/typeguards.test.ts
- test/utils/connect.ts
- website/sidebars.js
- yarn.lock
Update to work with Mongoose 6.0 and MongoDB 4.0
- https://github.com/Automattic/mongoose/issues/10506
- https://github.com/Automattic/mongoose/issues/10518
- https://github.com/Automattic/mongoose/issues/10576
- https://github.com/Automattic/mongoose/pull/10577
---
Note: `Related Issues` this time also includes `things noticed by upgrading (and made an issue about in mongoose), but not breaking`
Note: `Blocked By` means that until these are fixed, it is not expected mongoose 6.0 will even start to work with typegoose (even before release)
this is WIP, until 6.0 is released
Note: this PR will be rebased many times to update the mongoose version
PS: the base branch will be changed to `beta` once development starts on beta
> Update to Mongoose 6.0

- package.json
- yarn.lock
PR for upgrading dev-dependency `mongodb-memory-server` to `8.0.0` (or higher)
this is a PR now, to test in a different branch and to wait for later (this alone does not warrant a version release)
> dependencies(mongodb-memory-server): upgrade to 8.0.0

- package.json
Typgoose require mongoose@6.1.6 in package.json but require mongoose@6.2.0 in code.
> fix: error mongoose version

- website/docusaurus.config.js
- website/src/pages/index.js
Added a config key to `website/docusaurus.config.js` and used it in `website/src/pages/index.js` to prevent this:
Not gonna lie: I tried to `yarn run website` but couldn't for the life of me run docusaurus on my system.
Only two lines changed tho...
> Adds an actual description to website

- docs/api/decorators/prop.md
- prop.md
As you can see in the [link](https://typegoose.github.io/typegoose/docs/api/decorators/prop/) when you click to "read more here" nothing happens because there is case-sensitive typo.
> fix(docs): fix typo for prop.md

- docs/api/decorators/hooks.md
This PR fixes the Post-Hook documentation. There is a typo (Pre- instead of Post-Hook) and a false hint because there is no "this" inside of post hooks, instead one is accessing the document(s) affected by the post-hook-calling-method as shown in the example.
- None.
> docs(hooks): fix post-hook documentation

- package.json
Currently with single quotes, the `lint` script in `package.json` isn't usable on windows.
None
> fix(scripts): use double quotes in lint file glob

- docs/guides/syntax-notes.md
`ArraySubDocumentType<Kitten>` is just one Kitten subdocument, while in the context of these code samples it is meant to be an array.
> docs(syntax-notes): fix broken link, syntax error, and improve grammar

- docs/guides/quick-start-guide.md
- Fix typo
- Update Node.js requriements to match package.json engine semver range >=14
> docs(quick-start-guide.md): fix typo

- docs/api/decorators/searchIndexes.md
- docs/guides/all-decorators.md
- src/internal/constants.ts
- src/internal/schema.ts
- src/searchIndexes.ts
- src/typegoose.ts
- src/types.ts
- test/models/book.ts
- test/tests/searchIndexes.test.ts
- website/sidebars.js
MongoDB and `mongoose` now support adding search indexes to collections. Introduce a new decorator `@searchIndex()` that, similar to `@index`, adds a search index to a collection.
Search index support was added to `mongoose` in version `8.1.0`, however the type definition for `Schema.searchIndex()` didn't exist until `8.2.3`. Therefore in order to support this feature, update the `mongoose` dependencies to `~8.2.3`.
- N/A
> feat: add support for declaring search indexes

- src/typegoose.ts
The search index decorator (`@searchIndex()`) was added in `v12.3.0` in PR #921 but I neglected to actually export the decorator so it isn't currently available for use.
- N/A
> fix(searchindex): search index wasn't exported

- src/types.ts
Just fixing a tiny typo in the docs for autopopulate flag in `@prop` type.
> chore(docs): fix typo in autopopulate description
