typegoose/typegoose

- .github/Notes to Maintainers.md
- migrate_to_6.md
- src/prop.ts
- src/typegoose.ts
- src/typeguards.ts
- src/types.ts
- test/models/alias.ts
- test/models/car.ts
- test/models/hook1.ts
- test/models/hook2.ts
- test/models/indexweigths.ts
- test/models/internetUser.ts
- test/models/inventory.ts
- test/models/nestedObject.ts
- test/models/options.ts
- test/models/person.ts
- test/models/rating.ts
- test/models/select.ts
- test/models/stringValidators.ts
- test/models/user.ts
- test/models/userRefs.ts
- test/models/virtualprop.ts
- tsconfig.json
- outsourcing all functions in the Typegoose Class
-  refactoring all test-models for the new style
- adding migration note for it
fixes szokodiakos#356
fixes szokodiakos#373
> Refactoring for szokodiakos#356

- .gitignore
- src/prop.ts
- src/typegoose.ts
- test/index.test.ts
- test/models/discriminators.ts
- test/models/inheritanceClass.ts
- test/tests/inheritance.test.ts
- test/tests/shouldRun.test.ts
Enhancements for the inheritance feature. 
This code will add the features for: 
* Nested schema inheritance 
* Array Items inheritance
* @modelOptions inheritance 
* Multi-level inheritance
> Inheritance upgrade / Add more features 

- src/prop.ts
Fix we release Version 6.0.0 without this the refs feature will break. 
I would prefer to merge this before the 6.0.0 release. @hasezoey  what do you think?
> Fix ref name

- github-page/_docs/types/returnModelType.md
Addresses #57 : adapting documentation to avoid TS2344 and TS2742 errors.
fixes #57
> #57 : addressing TS2344 error for sample code.

- github-page/_docs/types/ref.md
- `@prop({ ref: 'ModelName' })` (#72)
- `@prop({ itemsRef: 'ModelName' })` (#72)
- Added Examples (#16)
> Added quotes to value of ref (and itemsRef).

- github-page/_docs/decorators/arrayProp.md
- github-page/_docs/decorators/mapProp.md
> Added examples for map and array props

- github-page/_data/navigation.yml
- github-page/_docs/functions/deleteModel.md
- src/typegoose.ts
- test/index.test.ts
- test/models/overwrittenUser.ts
- test/tests/errors.test.ts
- test/tests/overwrittenModel.test.ts
> Models can be deleted so that they can be overwritten

- src/typegoose.ts
- test/tests/overwrittenModel.test.ts
- test/utils/mongooseConnect.ts
> Fix deleting model definition from not main connection

- github-page/_docs/decorators/arrayProp.md
> Example for arrayProp of subdocuments

- github-page/_data/navigation.yml
- github-page/_guides/advanced/objectId.md
How to use ObjectId as a property correctly.
- #239
> Added a guide about how to use ObjectId for properties

- github-page/_guides/advanced/changeIDType.md
...+ fixed some of the English
> Explained how to disable the _id

- github-page/_guides/quick-start-guide.md
> Typos, grammar

- .github/ISSUE_TEMPLATE/bug.md
Thanks for all the work on Typegoose!
PS: maybe setting the browser's spell check language to English would be a good idea?
> Spell check

- docs/guides/quick-start-guide.md
- Getting Started - `@pre` hook example
closes #386
> Added Hooks example

- src/internal/utils.ts
- fixes incorrect URL to model options documentation
> Fix incorrect documentation URL

- src/index.ts
> fixed typo in "which"

- docs/api/decorators/prop.md
> Add default function example to Docs

- src/hooks.ts
Added pre and post hooks to aggregate query.
fixes https://github.com/typegoose/typegoose/issues/468
> Added aggregate hook

- docs/api/decorators/modelOptions.md
- docs/guides/error-warnings-details.md
- package-lock.json
- package.json
- src/internal/utils.ts
- src/types.ts
- test/tests/customName.test.ts
- test/tests/errors.test.ts
This enhancement will allow for a function to be added to the `customName` option to offer a bit more dynamic model naming capability.
closes #469 
Scott
> feat: adds the ability to use a function for customName

- docs/guides/faq.md
Corrected a simple typo in the FAQ: pleasae -> please
> Fixed typo

- docs/api/decorators/arrayProp.md
- docs/api/decorators/modelOptions.md
- docs/api/decorators/prop.md
- docs/api/decorators/queryMethod.md
- docs/api/functions/assertions.md
- docs/api/types/returnModelType.md
- docs/api/virtuals.md
- docs/guides/advanced/changeIDType.md
- docs/guides/advanced/class-transformer.md
- docs/guides/advanced/common-plugins.md
- docs/guides/error-warnings-details.md
- docs/guides/faq.md
- docs/guides/known-issues.md
- docs/guides/migrate-to-7.md
- docs/guides/quick-start-guide.md
- src/internal/utils.ts
> docs(general) - improve some grammar

- docs/guides/quick-start-guide.md
> Typo Fixed in Quick Start Guide

- docs/guides/advanced/reference-other-classes.md
I think an issue-template is overkill here, just fixed a small typo :)
> Small typo fix

- README.md
I just found a few English grammar errors in the README. I noticed that they're fine in the docs. I didn't open any issue regarding this because I thought it didn't need that much attention. 
P.S: It's okay if you think this PR is worthless.
> corrected usage of articles in readme

- src/internal/processProp.ts
- test/tests/errors.test.ts
- test/tests/ref.test.ts
This PR should allow the use of reference-maps
- ~~blocked by https://github.com/Automattic/mongoose/issues/10329 (which currently is not actually fixed)~~
~~Note: this PR is WIP, because of the mentioned blocking issue~~
> Fix reference maps

- docs/guides/advanced/non-nested-discriminators.md
- website/sidebars.js
Add an guide for "Non-Nested Discriminators"
- #565 
---
to run this documentation:
- clone the repository
- checkout the branch of this pr
- go inside `/website`
- run `yarn install`
- run `yarn run start`
- go to the website listed in the output
> docs(non-nested-dicriminators): add guide

- package.json
- test/globalSetup.ts
- yarn.lock
Update `mongodb-memory-server` to `7.0.0`
- Waiting for 7.0.0 to be released (https://github.com/nodkz/mongodb-memory-server/issues/456)
> dependencies(mongodb-memory-server): upgrade to version 7.0.0

- docs/api/decorators/prop.md
- docs/guides/error-warning-details.md
- docs/guides/integration-examples/deepkit-type.md
- docs/guides/mongoose-compatibility.md
- docs/guides/quick-start-guide.md
- package.json
- src/internal/processProp.ts
- src/typegoose.ts
- test/tests/__snapshots__/shouldRun.test.ts.snap
- test/tests/deepkitType.test.ts
- test/tests/discriminators.test.ts
- test/tests/shouldRun.test.ts
- yarn.lock
This is a PR, because mongoose 6.0.9 was not released yet
- re https://github.com/Automattic/mongoose/issues/10750
> Fix Passthrough being a Array while not using direct

- docs/guides/error-warning-details.md
- src/globalOptions.ts
- src/hooks.ts
- src/internal/errors.ts
- src/internal/processProp.ts
- src/internal/schema.ts
- src/internal/utils.ts
- src/typegoose.ts
- test/tests/__snapshots__/errors.test.ts.snap
- test/tests/__snapshots__/hooks.test.ts.snap
- test/tests/errors.test.ts
- test/tests/hooks.test.ts
- test/tests/overwrittenModel.test.ts
A PR to merge Error E020 and E021 into E027
currently not merged, because i plan on doing more error stuff that needs to be refactored before merging
> Merge e20 and e21 to e27

- docs/guides/advanced/manual-schema-modification.md
There was an error in line `const CatModelRaw = mongoose.model(getName(Cat), Cat);`. We should pass `CatSchema` instead of `Cat`.
-
> Fix documentation

- docs/api/decorators/prop.md
> docs(prop.md): fix typo

- .github/ISSUE_TEMPLATE/bug.md
- docs/guides/faq.md
- docs/guides/known-issues.md
- docs/guides/use-without-emitDecoratorMetadata.md
- website/README.md
> fix minor typos (missplling & grammar)

- test/tests/nestedDiscriminators.test.ts
Add a test for multi-dimensonal nested discriminators
currently blocked by https://github.com/Automattic/mongoose/issues/13201
- https://github.com/Automattic/mongoose/issues/13201
- https://github.com/Automattic/mongoose/pull/13202
> test(nestedDiscriminators): add test for multi-dimensonal nested discriminator arrays

- docs/guides/advanced/nested-discriminators.mdx
> docs(nested-discriminators.mdx): fix typo

- .github/CONTRIBUTING.md
Split from #894
These are just two typos. Cannot leave them (;
> chore: fix typos
